name: pokeguess

services:
  bot:
    build: ./
    restart: "unless-stopped"
    environment:
      - TOPGG_ENABLED=true
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_APPLICATION_ID=${DISCORD_APPLICATION_ID}
      - TOPGG_TOKEN=${TOPGG_TOKEN}
    volumes:
      - ./pokemons:/app/pokemons
    ports:
      - 8000:8000 # Prometheus
