[project]
name = "pokeguess"
version = "0.1.1"
description = "Who's That Pokemon! "
authors = [{ name = "ApolloRoboto", email = "Apollo_Roboto@outlook.com" }]
requires-python = ">=3.10"
urls = { Source = "https://github.com/ApolloRoboto/discord-pokeguess" }
readme = "readme.md"
license = "MIT"
keywords = ["discord", "bot", "pokemon", "game"]
classifiers = [
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Natural Language :: English",
    "Topic :: Games/Entertainment",
    "Typing :: Typed",
]
dependencies = [
    "python-dotenv==1.2.3",
    "requests==2.34.2",
    "discord.py==2.7.1",
    "pillow==12.3.0",
    "zalgo-text==0.6",
    "Levenshtein==0.27.4",
    "prometheus-client==0.26.0",
    "discord-ext-prometheus==0.2.1",
]

[project.scripts]
main = "pokeguess.__main__:run"

[build-system]
requires = ["uv_build>=0.12.5,<0.13"]
build-backend = "uv_build"
